version: "3.9"

x-postgres-variables: &postgres-variables
  POSTGRES_DB: "${DB__NAME}"
  POSTGRES_USER: "${DB__USER}"
  POSTGRES_PASSWORD: "${DB__PASSWORD}"


services:
  postgres:
    container_name: lct-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      <<: *postgres-variables
    ports:
      - "${DB__PORT}:5432"
